\set ON_ERROR_STOP on

SELECT 'CREATE ROLE geoeval LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'geoeval')
\gexec

ALTER ROLE geoeval LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;

SELECT 'CREATE ROLE "geoeval-callback" LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION CONNECTION LIMIT 10'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'geoeval-callback')
\gexec

ALTER ROLE "geoeval-callback" LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION CONNECTION LIMIT 10;

SELECT 'CREATE DATABASE geoeval OWNER geoeval'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'geoeval')
\gexec
