[Unit]
Wants=geoeval-api.service geoeval-web.service geoeval-worker.service geoeval-recharge-worker.service
After=geoeval-api.service geoeval-web.service geoeval-worker.service geoeval-recharge-worker.service
