\set ON_ERROR_STOP on

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'geoeval-app') THEN
    CREATE ROLE "geoeval-app" LOGIN;
  END IF;
END
$$;

ALTER ROLE "geoeval-app"
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
  CONNECTION LIMIT 24;
ALTER ROLE "geoeval-app" SET timezone TO 'UTC';

GRANT CONNECT ON DATABASE geoeval TO "geoeval-app";
REVOKE CREATE, TEMPORARY ON DATABASE geoeval FROM "geoeval-app";
GRANT USAGE ON SCHEMA public TO "geoeval-app";
REVOKE CREATE ON SCHEMA public FROM "geoeval-app";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "geoeval-app";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "geoeval-app";

ALTER DEFAULT PRIVILEGES FOR ROLE geoeval IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "geoeval-app";
ALTER DEFAULT PRIVILEGES FOR ROLE geoeval IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO "geoeval-app";
