/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FoundationController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/outbox/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_backlog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IdentityController_requestChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IdentityController_createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IdentityController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["IdentityController_deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandController_list"];
        put?: never;
        post: operations["BrandController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["BrandController_update"];
        trace?: never;
    };
    "/brands/{id}/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["BrandController_selectCurrent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_currentReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_reportHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_reportDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["EvaluationController_prepareDefinition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation-definitions/{definitionId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EvaluationController_startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation-runs/{runId}/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EvaluationController_retryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["NotificationController_markAllRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["NotificationController_markRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FoundationEffectResponse: {
            id: string;
            businessKey: string;
            result: string;
        };
        FoundationRecordResponse: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "ACCEPTED" | "PROCESSED";
            correlationId: string;
            effects: components["schemas"]["FoundationEffectResponse"][];
        };
        FoundationBacklogResponse: {
            pending: number;
            dispatched: number;
        };
        RequestChallengeRequest: {
            /** @example 13800138000 */
            mobile: string;
        };
        ChallengeResponse: {
            challengeId: string;
            expiresAt: string;
            /** @description Only returned by the local/test adapter */
            developmentCode?: string;
        };
        CompleteSessionRequest: {
            /** @example 13800138000 */
            mobile: string;
            challengeId: string;
            /** @example 246810 */
            code: string;
        };
        AccountResponse: {
            id: string;
            mobile: string;
            /** @enum {string} */
            role: "TERMINAL_CUSTOMER" | "OPERATIONS" | "ADMINISTRATOR" | "AGENT";
        };
        BrandResponse: {
            companyName?: string | null;
            primaryIndustry?: string | null;
            secondaryIndustry?: string | null;
            characteristicOne?: string | null;
            characteristicTwo?: string | null;
            province?: string | null;
            city?: string | null;
            district?: string | null;
            contactName?: string | null;
            contactMobile?: string | null;
            id: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED";
            readyForEvaluation: boolean;
            missingFields: string[];
            isCurrent: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BrandMutationRequest: {
            companyName?: string | null;
            primaryIndustry?: string | null;
            secondaryIndustry?: string | null;
            characteristicOne?: string | null;
            characteristicTwo?: string | null;
            province?: string | null;
            city?: string | null;
            district?: string | null;
            contactName?: string | null;
            contactMobile?: string | null;
        };
        EvaluationBrandSnapshotResponse: {
            companyName: string;
            primaryIndustry: string;
            secondaryIndustry: string;
            characteristicOne: string;
            characteristicTwo: string;
            province: string;
            city: string;
            district: string;
        };
        EvaluationQuestionResponse: {
            id: string;
            /** @enum {string} */
            kind: "BRAND_DIRECTED" | "INDUSTRY_RECOMMENDATION" | "CHARACTERISTIC_ONE" | "CHARACTERISTIC_TWO";
            ordinal: number;
            content: string;
        };
        EvaluationPlatformResponse: {
            key: string;
            label: string;
        };
        EvaluationRunResponse: {
            id: string;
            definitionId: string;
            brandId: string;
            /** @enum {string} */
            status: "EVALUATING" | "COMPLETED" | "PLEASE_RETRY";
            expectedSampleCount: number;
            processedSampleCount: number;
            validSampleCount: number;
            unavailableSampleCount: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EvaluationDefinitionResponse: {
            id: string;
            brandId: string;
            brandSnapshot: components["schemas"]["EvaluationBrandSnapshotResponse"];
            questions: components["schemas"]["EvaluationQuestionResponse"][];
            platforms: components["schemas"]["EvaluationPlatformResponse"][];
            run?: components["schemas"]["EvaluationRunResponse"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        EvaluationRecommendationIndexResponse: {
            score: number;
            stars: number;
            mentionRate: number;
            mentionCount: number;
            validOpenSampleCount: number;
        };
        EvaluationTypicalPositionResponse: {
            /** @enum {string} */
            kind: "NONE" | "SINGLE" | "RANGE";
            position?: number | null;
            first?: number | null;
            second?: number | null;
        };
        EvaluationCoverageResponse: {
            validSampleCount: number;
            totalSampleCount: number;
            missingSampleCount: number;
        };
        EvaluationReportOverviewResponse: {
            recommendationAssessment: string;
            brandPerception: string;
            recommendationIndex: components["schemas"]["EvaluationRecommendationIndexResponse"];
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
            coverage: components["schemas"]["EvaluationCoverageResponse"];
        };
        EvaluationPlatformReportResponse: {
            platformKey: string;
            platformLabel: string;
            validSampleCount: number;
            totalSampleCount: number;
            validOpenSampleCount: number;
            mentionCount: number;
            mentionRate: number;
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
        };
        EvaluationEvidenceSummaryResponse: {
            sampleCount: number;
            platforms: string[];
        };
        EvaluationThemeResponse: {
            themeId: string;
            label: string;
            summary: string;
            evidence: components["schemas"]["EvaluationEvidenceSummaryResponse"];
        };
        EvaluationThemesResponse: {
            positive: components["schemas"]["EvaluationThemeResponse"][];
            negative: components["schemas"]["EvaluationThemeResponse"][];
        };
        EvaluationCompetitorResponse: {
            groupId: string;
            displayName: string;
            occurrenceCount: number;
            platforms: string[];
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
        };
        EvaluationDirectionResponse: {
            directionId: string;
            currentProblem: string;
            recommendedDirection: string;
            intendedImprovement: string;
            evidence: components["schemas"]["EvaluationEvidenceSummaryResponse"];
        };
        EvaluationReportDocumentResponse: {
            overview: components["schemas"]["EvaluationReportOverviewResponse"];
            platforms: components["schemas"]["EvaluationPlatformReportResponse"][];
            themes: components["schemas"]["EvaluationThemesResponse"];
            competitors: components["schemas"]["EvaluationCompetitorResponse"][];
            directions: components["schemas"]["EvaluationDirectionResponse"][];
            limitations: string[];
        };
        EvaluationHighlightRangeResponse: {
            start: number;
            end: number;
            exactText: string;
            /** @enum {string} */
            kind: "TARGET" | "POSITIVE" | "NEGATIVE" | "MIXED";
        };
        EvaluationReportSampleResponse: {
            id: string;
            platformKey: string;
            platformLabel: string;
            /** @enum {string} */
            availability: "INCLUDED" | "NOT_INCLUDED";
            mentioned: boolean | null;
            position: number | null;
            cardInterpretation: string | null;
            originalAnswer: string | null;
            highlightUnavailable: boolean;
            highlights: components["schemas"]["EvaluationHighlightRangeResponse"][];
        };
        EvaluationReportQuestionResponse: {
            id: string;
            /** @enum {string} */
            kind: "BRAND_DIRECTED" | "INDUSTRY_RECOMMENDATION" | "CHARACTERISTIC_ONE" | "CHARACTERISTIC_TWO";
            ordinal: number;
            content: string;
            samples: components["schemas"]["EvaluationReportSampleResponse"][];
        };
        EvaluationReportResponse: {
            id: string;
            runId: string;
            definitionId: string;
            brandId: string;
            brandSnapshot: components["schemas"]["EvaluationBrandSnapshotResponse"];
            brandInformationChanged: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            acceptedAt: string;
            document: components["schemas"]["EvaluationReportDocumentResponse"];
            questions: components["schemas"]["EvaluationReportQuestionResponse"][];
        };
        CurrentEvaluationReportResponse: {
            report: components["schemas"]["EvaluationReportResponse"] | null;
        };
        EvaluationReportSummaryResponse: {
            id: string;
            runId: string;
            brandId: string;
            brandName: string;
            brandInformationChanged: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            acceptedAt: string;
            recommendationIndex: number;
            mentionRate: number;
            validSampleCount: number;
            totalSampleCount: number;
        };
        EvaluationReportHistoryResponse: {
            items: components["schemas"]["EvaluationReportSummaryResponse"][];
            nextCursor: string | null;
        };
        EvaluationReportNotificationTargetResponse: {
            /** @enum {string} */
            kind: "EVALUATION_REPORT";
            brandId: string;
            runId: string;
            reportId: string;
        };
        EvaluationRetryNotificationTargetResponse: {
            /** @enum {string} */
            kind: "EVALUATION_RETRY";
            brandId: string;
            runId: string;
        };
        NotificationResponse: {
            id: string;
            /** @enum {string} */
            kind: "EVALUATION_COMPLETED" | "EVALUATION_RETRY_REQUIRED";
            title: string;
            summary: string;
            target: components["schemas"]["EvaluationReportNotificationTargetResponse"] | components["schemas"]["EvaluationRetryNotificationTargetResponse"];
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            readAt: string | null;
        };
        NotificationListResponse: {
            items: components["schemas"]["NotificationResponse"][];
            unreadCount: number;
            nextCursor: string | null;
        };
        NotificationReadAllResponse: {
            unreadCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    FoundationController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationRecordResponse"];
                };
            };
        };
    };
    FoundationController_backlog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBacklogResponse"];
                };
            };
        };
    };
    FoundationController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationRecordResponse"];
                };
            };
        };
    };
    FoundationController_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentityController_requestChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestChallengeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
        };
    };
    IdentityController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteSessionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    IdentityController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    IdentityController_deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"][];
                };
            };
        };
    };
    BrandController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandMutationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    BrandController_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"] | null;
                };
            };
        };
    };
    BrandController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandMutationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    BrandController_selectCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    EvaluationController_currentReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentEvaluationReportResponse"];
                };
            };
        };
    };
    EvaluationController_reportHistory: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportHistoryResponse"];
                };
            };
        };
    };
    EvaluationController_reportDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportResponse"];
                };
            };
        };
    };
    EvaluationController_prepareDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDefinitionResponse"];
                };
            };
        };
    };
    EvaluationController_startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
        };
    };
    EvaluationController_retryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
        };
    };
    NotificationController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
        };
    };
    NotificationController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationReadAllResponse"];
                };
            };
        };
    };
    NotificationController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
        };
    };
    NotificationController_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
