/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FoundationController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/outbox/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_backlog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IdentityController_requestChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IdentityController_createSession"];
        delete: operations["IdentityController_deleteAllSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IdentityController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["IdentityController_deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountGovernanceController_list"];
        put?: never;
        post: operations["AccountGovernanceController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{accountId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AccountGovernanceController_changeStatus"];
        trace?: never;
    };
    "/admin/accounts/{accountId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AccountGovernanceController_changeRole"];
        trace?: never;
    };
    "/admin/accounts/{accountId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AccountGovernanceController_revokeSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountGovernanceController_audits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo-optimization/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GeoOptimizationController_workspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/article-generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GeoOptimizationController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/article-generations/{generationId}/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GeoOptimizationController_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/core-article/{articleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["GeoOptimizationController_save"];
        trace?: never;
    };
    "/brands/{brandId}/core-article/{articleId}/confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GeoOptimizationController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media-catalog/revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaCatalogController_revision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media-catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaCatalogController_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media-catalog/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaCatalogController_platforms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media-catalog/platforms/{platformId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaCatalogController_platform"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_platforms"];
        put?: never;
        post: operations["MediaAdminController_createPlatform"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/platforms/{platformId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_platform"];
        put?: never;
        post?: never;
        delete: operations["MediaAdminController_deletePlatform"];
        options?: never;
        head?: never;
        patch: operations["MediaAdminController_updatePlatform"];
        trace?: never;
    };
    "/admin/media/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_suppliers"];
        put?: never;
        post: operations["MediaAdminController_createSupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/suppliers/{supplierId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_supplier"];
        put?: never;
        post?: never;
        delete: operations["MediaAdminController_deleteSupplier"];
        options?: never;
        head?: never;
        patch: operations["MediaAdminController_updateSupplier"];
        trace?: never;
    };
    "/admin/media/resources/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["MediaAdminController_batchUpdateResourceStatus"];
        trace?: never;
    };
    "/admin/media/platforms/{platformId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaAdminController_createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["MediaAdminController_deleteResource"];
        options?: never;
        head?: never;
        patch: operations["MediaAdminController_updateResource"];
        trace?: never;
    };
    "/admin/media/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_audits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/publishing/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublishingPackageAdminController_list"];
        put?: never;
        post: operations["PublishingPackageAdminController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/publishing/packages/{packageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PublishingPackageAdminController_update"];
        trace?: never;
    };
    "/admin/publishing/packages/{packageId}/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublishingPackageAdminController_audits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishing/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublishingPackageCustomerController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["NotificationController_markAllRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["NotificationController_markRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_currentReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_reportHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_reportDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_observeDefinition"];
        put: operations["EvaluationController_prepareDefinition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation-question-preparations/{preparationId}/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EvaluationController_retryDefinitionPreparation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation-definitions/{definitionId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EvaluationController_startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation-runs/{runId}/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EvaluationController_retryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandController_list"];
        put?: never;
        post: operations["BrandController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["BrandController_update"];
        trace?: never;
    };
    "/brands/{id}/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["BrandController_selectCurrent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-reference-data/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandReferenceController_industries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-location-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StoreLocationVerificationController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FoundationEffectResponse: {
            id: string;
            businessKey: string;
            result: string;
        };
        FoundationRecordResponse: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "ACCEPTED" | "PROCESSED";
            correlationId: string;
            effects: components["schemas"]["FoundationEffectResponse"][];
        };
        FoundationBacklogResponse: {
            pending: number;
            dispatched: number;
        };
        RequestChallengeRequest: {
            /** @example 13800138000 */
            mobile: string;
        };
        ChallengeResponse: {
            challengeId: string;
            expiresAt: string;
            /** @description Only returned by the local/test adapter */
            developmentCode?: string;
        };
        CompleteSessionRequest: {
            /** @example 13800138000 */
            mobile: string;
            challengeId: string;
            /** @example 246810 */
            code: string;
        };
        AccountResponse: {
            id: string;
            mobile: string;
            /** @enum {string} */
            role: "TERMINAL_CUSTOMER" | "OPERATIONS" | "ADMINISTRATOR" | "AGENT";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            revision: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            lastAuthenticatedAt?: string | null;
        };
        SessionAuthenticationErrorResponse: {
            /** @enum {string} */
            code: "AUTHENTICATION_REQUIRED" | "ACCOUNT_INACTIVE" | "SESSION_REVOKED" | "SESSION_EXPIRED";
            message: string;
        };
        AccountSummaryResponse: {
            id: string;
            mobile: string;
            /** @enum {string} */
            role: "TERMINAL_CUSTOMER" | "OPERATIONS" | "ADMINISTRATOR" | "AGENT";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            revision: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            lastAuthenticatedAt?: string | null;
            activeSessionCount: number;
        };
        AccountListResponse: {
            items: components["schemas"]["AccountSummaryResponse"][];
            nextCursor?: string | null;
        };
        CreateInternalAccountRequest: {
            /** @example 13800138000 */
            mobile: string;
            /** @enum {string} */
            role: "OPERATIONS" | "ADMINISTRATOR" | "AGENT";
            reason: string;
        };
        ChangeAccountStatusRequest: {
            expectedRevision: number;
            reason: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
        };
        ChangeAccountRoleRequest: {
            expectedRevision: number;
            reason: string;
            /** @enum {string} */
            role: "OPERATIONS" | "ADMINISTRATOR" | "AGENT";
        };
        GovernedAccountMutationRequest: {
            expectedRevision: number;
            reason: string;
        };
        IdentityGovernanceAuditResponse: {
            id: string;
            /** @enum {string} */
            actorKind: "ACCOUNT" | "BOOTSTRAP";
            actorAccountId?: string | null;
            actorKeyId?: string | null;
            targetAccountId: string;
            /** @enum {string} */
            action: "BOOTSTRAP_ADMINISTRATOR" | "CREATE_INTERNAL_ACCOUNT" | "ACTIVATE_ACCOUNT" | "DEACTIVATE_ACCOUNT" | "CHANGE_INTERNAL_ROLE" | "REVOKE_ACCOUNT_SESSIONS";
            reason: string;
            beforeState?: {
                [key: string]: unknown;
            } | null;
            afterState: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        IdentityGovernanceAuditListResponse: {
            items: components["schemas"]["IdentityGovernanceAuditResponse"][];
            nextCursor?: string | null;
        };
        BrandCharacteristicResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            detail: string | null;
        };
        BrandArticleInformationRequest: {
            price: ({
                /** @enum {string} */
                mode: "RANGE";
                minimum: number;
                maximum: number;
            } | {
                /** @enum {string} */
                mode: "NEGOTIABLE";
            }) | null;
            suitableAudienceContexts: string[];
            supplementalBackground: string | null;
            desiredPositioning: string[];
        };
        StoreLocationCoordinateResponse: {
            longitude: number;
            latitude: number;
            /** @enum {string} */
            system: "GCJ_02";
        };
        RegionLabelResponse: {
            id: string;
            label: string;
        };
        CityRegionResponse: {
            id: string;
            label: string;
            /** @enum {string} */
            identityKind: "OFFICIAL_DIVISION" | "MUNICIPALITY_REPEAT" | "PROVINCE_DIRECT_GROUP";
            officialDivisionId?: string | null;
        };
        OfficialRegionNodeResponse: {
            id: string;
            label: string;
            officialCode: string;
            /** @enum {string} */
            officialLevel: "PROVINCE" | "PREFECTURE" | "COUNTY" | "TOWNSHIP";
        };
        DerivedOfficialRegionResponse: {
            sourceReleaseId: string;
            province: components["schemas"]["RegionLabelResponse"];
            city: components["schemas"]["CityRegionResponse"];
            terminal: components["schemas"]["OfficialRegionNodeResponse"];
            officialPath: components["schemas"]["OfficialRegionNodeResponse"][];
        };
        QueryLocalityResponse: {
            /** @enum {string} */
            kind: "BUSINESS_AREA" | "ADDRESS_LOCALITY";
            label: string;
        };
        BrandStoreLocationResponse: {
            placeName: string;
            formattedAddress: string;
            coordinate: components["schemas"]["StoreLocationCoordinateResponse"];
            officialRegion: components["schemas"]["DerivedOfficialRegionResponse"];
            queryLocality: components["schemas"]["QueryLocalityResponse"];
            /** Format: date-time */
            verifiedAt: string;
        };
        GeoOptimizationBrandResponse: {
            /** Format: uuid */
            id: string;
            companyName: string;
            primaryIndustryId: string | null;
            secondaryIndustryId: string | null;
            otherProductOrService: string | null;
            flagshipProductOrService: string | null;
            characteristics: components["schemas"]["BrandCharacteristicResponse"][];
            articleInformation: components["schemas"]["BrandArticleInformationRequest"];
            revision: number;
            primaryIndustryLabel: string | null;
            secondaryIndustryLabel: string | null;
            storeLocation: components["schemas"]["BrandStoreLocationResponse"] | null;
            readyForEvaluation: boolean;
            missingFields: string[];
            readyForArticleGeneration: boolean;
            articleInformationMissingFields: string[];
        };
        EvaluationEvidenceSummaryResponse: {
            sampleCount: number;
            platforms: string[];
        };
        EvaluationDirectionResponse: {
            directionId: string;
            currentProblem: string;
            recommendedDirection: string;
            intendedImprovement: string;
            evidence: components["schemas"]["EvaluationEvidenceSummaryResponse"];
        };
        GeoOptimizationGuidanceResponse: {
            /** Format: uuid */
            guidanceId: string;
            /** Format: date-time */
            acceptedAt: string;
            brandInformationChanged: boolean;
            customerDirections: components["schemas"]["EvaluationDirectionResponse"][];
        };
        GeoOptimizationGenerationFailureResponse: {
            code: string;
            message: string;
        };
        GeoOptimizationGenerationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            brandId: string;
            /** @enum {string} */
            status: "RUNNING" | "SUCCEEDED" | "FAILED" | "NOT_APPLIED";
            attemptCount: number;
            failure: components["schemas"]["GeoOptimizationGenerationFailureResponse"] | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GeoOptimizationArticleResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            brandId: string;
            title: string;
            bodyMarkdown: string;
            /** @enum {string} */
            status: "DRAFT" | "CONFIRMED";
            revision: number;
            confirmedRevision: number | null;
            /** Format: date-time */
            confirmedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GeoOptimizationFreshnessResponse: {
            brandInformationChanged: boolean;
            guidanceChanged: boolean;
        };
        GeoOptimizationWorkspaceResponse: {
            brand: components["schemas"]["GeoOptimizationBrandResponse"] | null;
            guidance: components["schemas"]["GeoOptimizationGuidanceResponse"] | null;
            latestGeneration: components["schemas"]["GeoOptimizationGenerationResponse"] | null;
            article: components["schemas"]["GeoOptimizationArticleResponse"] | null;
            articleFreshness: components["schemas"]["GeoOptimizationFreshnessResponse"] | null;
        };
        GenerateCoreArticleRequest: {
            idempotencyKey: string;
            expectedBrandRevision: number;
            expectedArticleRevision?: number;
        };
        SaveCoreArticleRequest: {
            expectedRevision: number;
            title: string;
            bodyMarkdown: string;
        };
        ConfirmCoreArticleRequest: {
            expectedRevision: number;
        };
        MediaCatalogRevisionResponse: {
            revision: string;
        };
        MediaCategoryResponse: {
            /** @enum {string} */
            id: "CENTRAL_MEDIA" | "PORTAL_MEDIA" | "LOCAL_MEDIA" | "VERTICAL_MEDIA" | "CONTENT_PLATFORM";
            label: string;
        };
        MediaResourceExampleResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            /** @enum {string} */
            publicationMode: "FIRST_PUBLISH" | "REPOST";
        };
        MediaPlatformCustomerResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            description?: string | null;
            logoUrl?: string | null;
            /** @enum {string} */
            regionScope: "DOMESTIC" | "OVERSEAS";
            categories: ("CENTRAL_MEDIA" | "PORTAL_MEDIA" | "LOCAL_MEDIA" | "VERTICAL_MEDIA" | "CONTENT_PLATFORM")[];
            pointPrice: number;
            revision: number;
            examples: components["schemas"]["MediaResourceExampleResponse"][];
        };
        MediaPlatformPageResponse: {
            items: components["schemas"]["MediaPlatformCustomerResponse"][];
            /** Format: uuid */
            nextCursor?: string | null;
        };
        MediaPlatformAdminResponse: {
            /** Format: uuid */
            id: string;
            normalizedName: string;
            displayName: string;
            aliases: string[];
            description?: string | null;
            logoUrl?: string | null;
            /** @enum {string} */
            regionScope: "DOMESTIC" | "OVERSEAS";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            pointPrice?: number | null;
            categories: ("CENTRAL_MEDIA" | "PORTAL_MEDIA" | "LOCAL_MEDIA" | "VERTICAL_MEDIA" | "CONTENT_PLATFORM")[];
            revision: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaPlatformCreateRequest: {
            displayName: string;
            /** @default [] */
            aliases: string[];
            description?: string | null;
            logoUrl?: string | null;
            /**
             * @default DOMESTIC
             * @enum {string}
             */
            regionScope: "DOMESTIC" | "OVERSEAS";
            /**
             * @default INACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            pointPrice?: number | null;
            categories: ("CENTRAL_MEDIA" | "PORTAL_MEDIA" | "LOCAL_MEDIA" | "VERTICAL_MEDIA" | "CONTENT_PLATFORM")[];
        };
        MediaPlatformUpdateRequest: {
            reason: string;
            displayName?: string;
            aliases?: string[];
            description?: string | null;
            logoUrl?: string | null;
            /** @enum {string} */
            regionScope?: "DOMESTIC" | "OVERSEAS";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            pointPrice?: number | null;
            categories?: ("CENTRAL_MEDIA" | "PORTAL_MEDIA" | "LOCAL_MEDIA" | "VERTICAL_MEDIA" | "CONTENT_PLATFORM")[];
            expectedRevision: number;
        };
        MediaDeleteOwnerRequest: {
            reason: string;
            expectedRevision: number;
        };
        MediaSupplierResponse: {
            /** Format: uuid */
            id: string;
            normalizedName: string;
            displayName: string;
            contactName?: string | null;
            contactMethod?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            notes?: string | null;
            revision: number;
            resourceCount: number;
            platformCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaSupplierAssociationResponse: {
            /** Format: uuid */
            resourceId: string;
            resourceName: string;
            /** @enum {string} */
            resourceStatus: "ACTIVE" | "INACTIVE";
            /** @enum {string} */
            effectiveStatus: "ACTIVE" | "RESOURCE_INACTIVE" | "SUPPLIER_INACTIVE";
            resourceRevision: number;
            /** Format: uuid */
            platformId: string;
            platformDisplayName: string;
        };
        MediaSupplierDetailResponse: {
            /** Format: uuid */
            id: string;
            normalizedName: string;
            displayName: string;
            contactName?: string | null;
            contactMethod?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            notes?: string | null;
            revision: number;
            resourceCount: number;
            platformCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            resources: components["schemas"]["MediaSupplierAssociationResponse"][];
        };
        MediaSupplierCreateRequest: {
            displayName: string;
            contactName?: string | null;
            contactMethod?: string | null;
            /**
             * @default INACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            notes?: string | null;
        };
        MediaSupplierUpdateRequest: {
            reason: string;
            displayName?: string;
            contactName?: string | null;
            contactMethod?: string | null;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            notes?: string | null;
            expectedRevision: number;
        };
        MediaResourceBatchItemRequest: {
            /** Format: uuid */
            resourceId: string;
            expectedRevision: number;
        };
        MediaResourceBatchStatusRequest: {
            reason: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            items: components["schemas"]["MediaResourceBatchItemRequest"][];
        };
        MediaResourceAdminResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            platformId: string;
            /** Format: uuid */
            supplierId: string;
            resourceName: string;
            accountIdentifier?: string | null;
            accountUrl?: string | null;
            /** @enum {string} */
            publicationMode: "FIRST_PUBLISH" | "REPOST";
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** @enum {string} */
            effectiveStatus: "ACTIVE" | "RESOURCE_INACTIVE" | "SUPPLIER_INACTIVE";
            /** @enum {string} */
            publicVisibility: "HIDDEN" | "FULL" | "MASKED";
            publicAlias?: string | null;
            /** @enum {string} */
            qualityTier: "HIGH" | "MEDIUM" | "LOW";
            procurementCostYuan?: number | null;
            caseUrl?: string | null;
            publicationNotes?: string | null;
            supplier: components["schemas"]["MediaSupplierResponse"];
            revision: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaResourceCreateRequest: {
            /** Format: uuid */
            platformId: string;
            /** Format: uuid */
            supplierId: string;
            resourceName: string;
            accountIdentifier?: string | null;
            accountUrl?: string | null;
            /**
             * @default FIRST_PUBLISH
             * @enum {string}
             */
            publicationMode: "FIRST_PUBLISH" | "REPOST";
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * @default HIDDEN
             * @enum {string}
             */
            publicVisibility: "HIDDEN" | "FULL" | "MASKED";
            publicAlias?: string | null;
            /**
             * @default MEDIUM
             * @enum {string}
             */
            qualityTier: "HIGH" | "MEDIUM" | "LOW";
            procurementCostYuan?: number | null;
            caseUrl?: string | null;
            publicationNotes?: string | null;
        };
        MediaResourceUpdateRequest: {
            reason: string;
            /** Format: uuid */
            platformId?: string;
            /** Format: uuid */
            supplierId?: string;
            resourceName?: string;
            accountIdentifier?: string | null;
            accountUrl?: string | null;
            /** @enum {string} */
            publicationMode?: "FIRST_PUBLISH" | "REPOST";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            /** @enum {string} */
            publicVisibility?: "HIDDEN" | "FULL" | "MASKED";
            publicAlias?: string | null;
            /** @enum {string} */
            qualityTier?: "HIGH" | "MEDIUM" | "LOW";
            procurementCostYuan?: number | null;
            caseUrl?: string | null;
            publicationNotes?: string | null;
            expectedRevision: number;
        };
        MediaResourceDeleteRequest: {
            reason: string;
            expectedRevision: number;
            /** @default false */
            deleteUnreferencedSupplier: boolean;
            expectedSupplierRevision?: number;
        };
        MediaResourceDeleteResponse: {
            /** Format: uuid */
            resourceId: string;
            /** Format: uuid */
            supplierId: string;
            supplierDeleted: boolean;
        };
        MediaCatalogAuditResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actorAccountId: string;
            entityType: string;
            /** Format: uuid */
            entityId: string;
            action: string;
            reason: string;
            beforeState?: Record<string, never> | null;
            afterState?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        PublishingPackageAdminResponse: {
            name: string;
            quantity: number;
            pointPrice: number;
            /** @enum {string} */
            status: "INACTIVE" | "ACTIVE";
            platformIds: string[];
            /** Format: uuid */
            id: string;
            revision: number;
        };
        PublishingPackageCreateRequest: {
            name: string;
            quantity: number;
            pointPrice: number;
            /** @enum {string} */
            status: "INACTIVE" | "ACTIVE";
            platformIds: string[];
        };
        PublishingPackageUpdateRequest: {
            name: string;
            quantity: number;
            pointPrice: number;
            /** @enum {string} */
            status: "INACTIVE" | "ACTIVE";
            platformIds: string[];
            expectedRevision: number;
            reason: string;
        };
        PublishingPackageAuditResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actorAccountId: string;
            reason: string;
            /** Format: date-time */
            createdAt: string;
            beforeState: components["schemas"]["PublishingPackageAdminResponse"] | null;
            afterState: components["schemas"]["PublishingPackageAdminResponse"];
        };
        PublishingPackageScopeResponse: {
            /** Format: uuid */
            platformId: string;
            displayName: string;
        };
        PublishingPackageCustomerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            quantity: number;
            pointPrice: number;
            revision: number;
            buyable: boolean;
            scope: components["schemas"]["PublishingPackageScopeResponse"][];
        };
        EvaluationReportNotificationTargetResponse: {
            /** @enum {string} */
            kind: "EVALUATION_REPORT";
            brandId: string;
            runId: string;
            reportId: string;
        };
        EvaluationRetryNotificationTargetResponse: {
            /** @enum {string} */
            kind: "EVALUATION_RETRY";
            brandId: string;
            runId: string;
        };
        NotificationResponse: {
            id: string;
            /** @enum {string} */
            kind: "EVALUATION_COMPLETED" | "EVALUATION_RETRY_REQUIRED";
            title: string;
            summary: string;
            target: components["schemas"]["EvaluationReportNotificationTargetResponse"] | components["schemas"]["EvaluationRetryNotificationTargetResponse"];
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            readAt: string | null;
        };
        NotificationListResponse: {
            items: components["schemas"]["NotificationResponse"][];
            unreadCount: number;
            nextCursor: string | null;
        };
        NotificationReadAllResponse: {
            unreadCount: number;
        };
        EvaluationBrandSnapshotResponse: {
            companyName: string;
            primaryIndustry: string;
            secondaryIndustry: string;
            characteristicOne: string;
            characteristicTwo: string;
            province: string;
            city: string;
            district: string;
        };
        EvaluationQuestionResponse: {
            id: string;
            /** @enum {string} */
            kind: "BRAND_DIRECTED" | "INDUSTRY_RECOMMENDATION" | "CHARACTERISTIC_ONE" | "CHARACTERISTIC_TWO";
            ordinal: number;
            content: string;
        };
        EvaluationPlatformResponse: {
            key: string;
            label: string;
        };
        EvaluationRunResponse: {
            id: string;
            definitionId: string;
            brandId: string;
            /** @enum {string} */
            status: "EVALUATING" | "COMPLETED" | "PLEASE_RETRY";
            expectedSampleCount: number;
            processedSampleCount: number;
            validSampleCount: number;
            unavailableSampleCount: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EvaluationDefinitionResponse: {
            id: string;
            brandId: string;
            brandSnapshot: components["schemas"]["EvaluationBrandSnapshotResponse"];
            questions: components["schemas"]["EvaluationQuestionResponse"][];
            platforms: components["schemas"]["EvaluationPlatformResponse"][];
            run?: components["schemas"]["EvaluationRunResponse"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        EvaluationDefinitionPreparationResponse: {
            /** @enum {string} */
            status: "PREPARING" | "READY" | "PLEASE_RETRY";
            preparationId: string | null;
            definition: components["schemas"]["EvaluationDefinitionResponse"] | null;
        };
        CurrentEvaluationDefinitionPreparationResponse: {
            preparation: components["schemas"]["EvaluationDefinitionPreparationResponse"] | null;
        };
        EvaluationRecommendationIndexResponse: {
            score: number;
            stars: number;
            mentionRate: number;
            mentionCount: number;
            validOpenSampleCount: number;
        };
        EvaluationTypicalPositionResponse: {
            /** @enum {string} */
            kind: "NONE" | "SINGLE" | "RANGE";
            position?: number | null;
            first?: number | null;
            second?: number | null;
        };
        EvaluationCoverageResponse: {
            validSampleCount: number;
            totalSampleCount: number;
            missingSampleCount: number;
        };
        EvaluationReportOverviewResponse: {
            recommendationAssessment: string;
            brandPerception: string;
            recommendationIndex: components["schemas"]["EvaluationRecommendationIndexResponse"];
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
            coverage: components["schemas"]["EvaluationCoverageResponse"];
        };
        EvaluationPlatformReportResponse: {
            platformKey: string;
            platformLabel: string;
            validSampleCount: number;
            totalSampleCount: number;
            validOpenSampleCount: number;
            mentionCount: number;
            mentionRate: number;
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
        };
        EvaluationThemeResponse: {
            themeId: string;
            label: string;
            summary: string;
            evidence: components["schemas"]["EvaluationEvidenceSummaryResponse"];
        };
        EvaluationThemesResponse: {
            positive: components["schemas"]["EvaluationThemeResponse"][];
            negative: components["schemas"]["EvaluationThemeResponse"][];
        };
        EvaluationCompetitorResponse: {
            groupId: string;
            displayName: string;
            occurrenceCount: number;
            platforms: string[];
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
        };
        EvaluationReportDocumentResponse: {
            overview: components["schemas"]["EvaluationReportOverviewResponse"];
            platforms: components["schemas"]["EvaluationPlatformReportResponse"][];
            themes: components["schemas"]["EvaluationThemesResponse"];
            competitors: components["schemas"]["EvaluationCompetitorResponse"][];
            directions: components["schemas"]["EvaluationDirectionResponse"][];
            limitations: string[];
        };
        EvaluationHighlightRangeResponse: {
            start: number;
            end: number;
            exactText: string;
            /** @enum {string} */
            kind: "TARGET" | "POSITIVE" | "NEGATIVE" | "MIXED";
        };
        EvaluationReportSampleResponse: {
            id: string;
            platformKey: string;
            platformLabel: string;
            /** @enum {string} */
            availability: "INCLUDED" | "NOT_INCLUDED";
            mentioned: boolean | null;
            position: number | null;
            cardInterpretation: string | null;
            originalAnswer: string | null;
            highlightUnavailable: boolean;
            highlights: components["schemas"]["EvaluationHighlightRangeResponse"][];
        };
        EvaluationReportQuestionResponse: {
            id: string;
            /** @enum {string} */
            kind: "BRAND_DIRECTED" | "INDUSTRY_RECOMMENDATION" | "CHARACTERISTIC_ONE" | "CHARACTERISTIC_TWO";
            ordinal: number;
            content: string;
            samples: components["schemas"]["EvaluationReportSampleResponse"][];
        };
        EvaluationReportResponse: {
            id: string;
            runId: string;
            definitionId: string;
            brandId: string;
            brandSnapshot: components["schemas"]["EvaluationBrandSnapshotResponse"];
            brandInformationChanged: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            acceptedAt: string;
            document: components["schemas"]["EvaluationReportDocumentResponse"];
            questions: components["schemas"]["EvaluationReportQuestionResponse"][];
        };
        CurrentEvaluationReportResponse: {
            report: components["schemas"]["EvaluationReportResponse"] | null;
        };
        EvaluationReportSummaryResponse: {
            id: string;
            runId: string;
            brandId: string;
            brandName: string;
            brandInformationChanged: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            acceptedAt: string;
            recommendationIndex: number;
            mentionRate: number;
            validSampleCount: number;
            totalSampleCount: number;
        };
        EvaluationReportHistoryResponse: {
            items: components["schemas"]["EvaluationReportSummaryResponse"][];
            nextCursor: string | null;
        };
        BrandResponse: {
            id: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED";
            companyName: string;
            primaryIndustryId?: string | null;
            secondaryIndustryId?: string | null;
            otherProductOrService?: string | null;
            flagshipProductOrService?: string | null;
            characteristics: components["schemas"]["BrandCharacteristicResponse"][];
            articleInformation: components["schemas"]["BrandArticleInformationRequest"];
            revision: number;
            contactName?: string | null;
            contactMobile?: string | null;
            primaryIndustryLabel?: string | null;
            secondaryIndustryLabel?: string | null;
            storeLocation?: components["schemas"]["BrandStoreLocationResponse"] | null;
            readyForEvaluation: boolean;
            missingFields: string[];
            readyForArticleGeneration: boolean;
            articleInformationMissingFields: string[];
            isCurrent: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BrandCharacteristicMutationRequest: {
            /** Format: uuid */
            id?: string;
            title: string;
            detail?: string | null;
        };
        BrandLocationChangeRequest: {
            /** @enum {string} */
            action: "REMOVE" | "REPLACE";
            verificationReceipt?: string;
        };
        BrandMutationRequest: {
            companyName?: string | null;
            primaryIndustryId?: string | null;
            secondaryIndustryId?: string | null;
            otherProductOrService?: string | null;
            flagshipProductOrService?: string | null;
            characteristics?: components["schemas"]["BrandCharacteristicMutationRequest"][];
            articleInformation?: components["schemas"]["BrandArticleInformationRequest"];
            contactName?: string | null;
            contactMobile?: string | null;
            locationChange?: components["schemas"]["BrandLocationChangeRequest"];
        };
        BrandUpdateRequest: {
            companyName?: string | null;
            primaryIndustryId?: string | null;
            secondaryIndustryId?: string | null;
            otherProductOrService?: string | null;
            flagshipProductOrService?: string | null;
            characteristics?: components["schemas"]["BrandCharacteristicMutationRequest"][];
            articleInformation?: components["schemas"]["BrandArticleInformationRequest"];
            contactName?: string | null;
            contactMobile?: string | null;
            locationChange?: components["schemas"]["BrandLocationChangeRequest"];
            expectedRevision: number;
        };
        IndustrySecondaryOptionResponse: {
            id: string;
            label: string;
            isOther: boolean;
        };
        IndustryPrimaryOptionResponse: {
            id: string;
            label: string;
            secondaryIndustries: components["schemas"]["IndustrySecondaryOptionResponse"][];
        };
        IndustryCatalogResponse: {
            catalogId: string;
            version: string;
            contentHash: string;
            primaryIndustries: components["schemas"]["IndustryPrimaryOptionResponse"][];
        };
        StoreLocationVerificationRequest: {
            brandId?: string;
            searchInput: string;
            providerPlaceId: string;
        };
        StoreLocationPreviewResponse: {
            placeName: string;
            formattedAddress: string;
            coordinate: components["schemas"]["StoreLocationCoordinateResponse"];
            officialRegion: components["schemas"]["DerivedOfficialRegionResponse"];
        };
        StoreLocationVerificationResponse: {
            targetBrandId: string;
            verificationReceipt: string;
            /** Format: date-time */
            expiresAt: string;
            locationPreview: components["schemas"]["StoreLocationPreviewResponse"];
            queryLocality: components["schemas"]["QueryLocalityResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    FoundationController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationRecordResponse"];
                };
            };
        };
    };
    FoundationController_backlog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBacklogResponse"];
                };
            };
        };
    };
    FoundationController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationRecordResponse"];
                };
            };
        };
    };
    FoundationController_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentityController_requestChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestChallengeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
        };
    };
    IdentityController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteSessionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    IdentityController_deleteAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentityController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionAuthenticationErrorResponse"];
                };
            };
        };
    };
    IdentityController_deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountGovernanceController_list: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                status?: string;
                role?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
        };
    };
    AccountGovernanceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInternalAccountRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    AccountGovernanceController_changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeAccountStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    AccountGovernanceController_changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeAccountRoleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    AccountGovernanceController_revokeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GovernedAccountMutationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    AccountGovernanceController_audits: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                targetAccountId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityGovernanceAuditListResponse"];
                };
            };
        };
    };
    GeoOptimizationController_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoOptimizationWorkspaceResponse"];
                };
            };
        };
    };
    GeoOptimizationController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCoreArticleRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoOptimizationGenerationResponse"];
                };
            };
        };
    };
    GeoOptimizationController_retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: string;
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoOptimizationGenerationResponse"];
                };
            };
        };
    };
    GeoOptimizationController_save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: string;
                brandId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCoreArticleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoOptimizationArticleResponse"];
                };
            };
        };
    };
    GeoOptimizationController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                articleId: string;
                brandId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmCoreArticleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoOptimizationArticleResponse"];
                };
            };
        };
    };
    MediaCatalogController_revision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCatalogRevisionResponse"];
                };
            };
        };
    };
    MediaCatalogController_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCategoryResponse"][];
                };
            };
        };
    };
    MediaCatalogController_platforms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformPageResponse"];
                };
            };
        };
    };
    MediaCatalogController_platform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformCustomerResponse"];
                };
            };
        };
    };
    MediaAdminController_platforms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"][];
                };
            };
        };
    };
    MediaAdminController_createPlatform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaPlatformCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_platform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_deletePlatform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaDeleteOwnerRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaAdminController_updatePlatform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaPlatformUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_suppliers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaSupplierResponse"][];
                };
            };
        };
    };
    MediaAdminController_createSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaSupplierCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaSupplierResponse"];
                };
            };
        };
    };
    MediaAdminController_supplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaSupplierDetailResponse"];
                };
            };
        };
    };
    MediaAdminController_deleteSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaDeleteOwnerRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaAdminController_updateSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaSupplierUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaSupplierResponse"];
                };
            };
        };
    };
    MediaAdminController_batchUpdateResourceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaResourceBatchStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResourceAdminResponse"][];
                };
            };
        };
    };
    MediaAdminController_resources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResourceAdminResponse"][];
                };
            };
        };
    };
    MediaAdminController_createResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaResourceCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResourceAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaResourceDeleteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResourceDeleteResponse"];
                };
            };
        };
    };
    MediaAdminController_updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaResourceUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResourceAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_audits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCatalogAuditResponse"][];
                };
            };
        };
    };
    PublishingPackageAdminController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingPackageAdminResponse"][];
                };
            };
        };
    };
    PublishingPackageAdminController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishingPackageCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingPackageAdminResponse"];
                };
            };
        };
    };
    PublishingPackageAdminController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                packageId: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishingPackageUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingPackageAdminResponse"];
                };
            };
        };
    };
    PublishingPackageAdminController_audits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                packageId: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingPackageAuditResponse"][];
                };
            };
        };
    };
    PublishingPackageCustomerController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingPackageCustomerResponse"][];
                };
            };
        };
    };
    NotificationController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
        };
    };
    NotificationController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationReadAllResponse"];
                };
            };
        };
    };
    NotificationController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
        };
    };
    NotificationController_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EvaluationController_currentReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentEvaluationReportResponse"];
                };
            };
        };
    };
    EvaluationController_reportHistory: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportHistoryResponse"];
                };
            };
        };
    };
    EvaluationController_reportDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportResponse"];
                };
            };
        };
    };
    EvaluationController_observeDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentEvaluationDefinitionPreparationResponse"];
                };
            };
        };
    };
    EvaluationController_prepareDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDefinitionPreparationResponse"];
                };
            };
        };
    };
    EvaluationController_retryDefinitionPreparation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preparationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDefinitionPreparationResponse"];
                };
            };
        };
    };
    EvaluationController_startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
        };
    };
    EvaluationController_retryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
        };
    };
    BrandController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"][];
                };
            };
        };
    };
    BrandController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandMutationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    BrandController_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"] | null;
                };
            };
        };
    };
    BrandController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    BrandController_selectCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    BrandReferenceController_industries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryCatalogResponse"];
                };
            };
        };
    };
    StoreLocationVerificationController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreLocationVerificationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreLocationVerificationResponse"];
                };
            };
        };
    };
}
