/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FoundationController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/outbox/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_backlog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundation/records/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoundationController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IdentityController_requestChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IdentityController_createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IdentityController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["IdentityController_deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandController_list"];
        put?: never;
        post: operations["BrandController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["BrandController_update"];
        trace?: never;
    };
    "/brands/{id}/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["BrandController_selectCurrent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-reference-data/industries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandReferenceController_industries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-reference-data/regions/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandReferenceController_provinces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-reference-data/regions/provinces/{provinceId}/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandReferenceController_cities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-reference-data/regions/provinces/{provinceId}/cities/{cityId}/terminals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandReferenceController_terminals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_currentReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_reportHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EvaluationController_reportDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brandId}/evaluation-definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["EvaluationController_prepareDefinition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation-definitions/{definitionId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EvaluationController_startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation-runs/{runId}/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EvaluationController_retryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media-catalog/revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaCatalogController_revision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media-catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaCatalogController_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media-catalog/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaCatalogController_platforms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media-catalog/platforms/{platformId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaCatalogController_platform"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_platforms"];
        put?: never;
        post: operations["MediaAdminController_createPlatform"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/platforms/{platformId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_platform"];
        put?: never;
        post?: never;
        delete: operations["MediaAdminController_deletePlatform"];
        options?: never;
        head?: never;
        patch: operations["MediaAdminController_updatePlatform"];
        trace?: never;
    };
    "/admin/media/platforms/{platformId}/listing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MediaAdminController_listing"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_sources"];
        put?: never;
        post: operations["MediaAdminController_createSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["MediaAdminController_deleteSource"];
        options?: never;
        head?: never;
        patch: operations["MediaAdminController_updateSource"];
        trace?: never;
    };
    "/admin/media/platforms/{platformId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaAdminController_createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["MediaAdminController_deleteResource"];
        options?: never;
        head?: never;
        patch: operations["MediaAdminController_updateResource"];
        trace?: never;
    };
    "/admin/media/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaAdminController_audits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["NotificationController_markAllRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["NotificationController_markRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FoundationEffectResponse: {
            id: string;
            businessKey: string;
            result: string;
        };
        FoundationRecordResponse: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "ACCEPTED" | "PROCESSED";
            correlationId: string;
            effects: components["schemas"]["FoundationEffectResponse"][];
        };
        FoundationBacklogResponse: {
            pending: number;
            dispatched: number;
        };
        RequestChallengeRequest: {
            /** @example 13800138000 */
            mobile: string;
        };
        ChallengeResponse: {
            challengeId: string;
            expiresAt: string;
            /** @description Only returned by the local/test adapter */
            developmentCode?: string;
        };
        CompleteSessionRequest: {
            /** @example 13800138000 */
            mobile: string;
            challengeId: string;
            /** @example 246810 */
            code: string;
        };
        AccountResponse: {
            id: string;
            mobile: string;
            /** @enum {string} */
            role: "TERMINAL_CUSTOMER" | "OPERATIONS" | "ADMINISTRATOR" | "AGENT";
        };
        BrandResponse: {
            companyName?: string | null;
            primaryIndustryId?: string | null;
            secondaryIndustryId?: string | null;
            otherProductOrService?: string | null;
            characteristicOne?: string | null;
            characteristicTwo?: string | null;
            provinceRegionId?: string | null;
            cityRegionId?: string | null;
            terminalRegionId?: string | null;
            contactName?: string | null;
            contactMobile?: string | null;
            id: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED";
            primaryIndustryLabel?: string | null;
            secondaryIndustryLabel?: string | null;
            provinceRegionLabel?: string | null;
            cityRegionLabel?: string | null;
            terminalRegionLabel?: string | null;
            /** @enum {string|null} */
            terminalRegionLevel?: "COUNTY" | "TOWNSHIP" | null;
            readyForEvaluation: boolean;
            missingFields: string[];
            isCurrent: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BrandMutationRequest: {
            companyName?: string | null;
            primaryIndustryId?: string | null;
            secondaryIndustryId?: string | null;
            otherProductOrService?: string | null;
            characteristicOne?: string | null;
            characteristicTwo?: string | null;
            provinceRegionId?: string | null;
            cityRegionId?: string | null;
            terminalRegionId?: string | null;
            contactName?: string | null;
            contactMobile?: string | null;
        };
        IndustrySecondaryOptionResponse: {
            id: string;
            label: string;
            isOther: boolean;
        };
        IndustryPrimaryOptionResponse: {
            id: string;
            label: string;
            secondaryIndustries: components["schemas"]["IndustrySecondaryOptionResponse"][];
        };
        IndustryCatalogResponse: {
            catalogId: string;
            version: string;
            contentHash: string;
            primaryIndustries: components["schemas"]["IndustryPrimaryOptionResponse"][];
        };
        RegionOptionResponse: {
            id: string;
            label: string;
        };
        RegionOptionListResponse: {
            sourceReleaseId: string;
            contentHash: string;
            options: components["schemas"]["RegionOptionResponse"][];
        };
        CityRegionOptionResponse: {
            id: string;
            label: string;
            /** @enum {string} */
            identityKind: "OFFICIAL_DIVISION" | "MUNICIPALITY_REPEAT" | "PROVINCE_DIRECT_GROUP";
        };
        CityRegionOptionListResponse: {
            sourceReleaseId: string;
            contentHash: string;
            options: components["schemas"]["CityRegionOptionResponse"][];
        };
        TerminalRegionOptionResponse: {
            id: string;
            label: string;
            /** @enum {string} */
            officialLevel: "COUNTY" | "TOWNSHIP";
        };
        TerminalRegionOptionListResponse: {
            sourceReleaseId: string;
            contentHash: string;
            options: components["schemas"]["TerminalRegionOptionResponse"][];
        };
        EvaluationBrandSnapshotResponse: {
            companyName: string;
            primaryIndustry: string;
            secondaryIndustry: string;
            characteristicOne: string;
            characteristicTwo: string;
            province: string;
            city: string;
            district: string;
        };
        EvaluationQuestionResponse: {
            id: string;
            /** @enum {string} */
            kind: "BRAND_DIRECTED" | "INDUSTRY_RECOMMENDATION" | "CHARACTERISTIC_ONE" | "CHARACTERISTIC_TWO";
            ordinal: number;
            content: string;
        };
        EvaluationPlatformResponse: {
            key: string;
            label: string;
        };
        EvaluationRunResponse: {
            id: string;
            definitionId: string;
            brandId: string;
            /** @enum {string} */
            status: "EVALUATING" | "COMPLETED" | "PLEASE_RETRY";
            expectedSampleCount: number;
            processedSampleCount: number;
            validSampleCount: number;
            unavailableSampleCount: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EvaluationDefinitionResponse: {
            id: string;
            brandId: string;
            brandSnapshot: components["schemas"]["EvaluationBrandSnapshotResponse"];
            questions: components["schemas"]["EvaluationQuestionResponse"][];
            platforms: components["schemas"]["EvaluationPlatformResponse"][];
            run?: components["schemas"]["EvaluationRunResponse"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        EvaluationRecommendationIndexResponse: {
            score: number;
            stars: number;
            mentionRate: number;
            mentionCount: number;
            validOpenSampleCount: number;
        };
        EvaluationTypicalPositionResponse: {
            /** @enum {string} */
            kind: "NONE" | "SINGLE" | "RANGE";
            position?: number | null;
            first?: number | null;
            second?: number | null;
        };
        EvaluationCoverageResponse: {
            validSampleCount: number;
            totalSampleCount: number;
            missingSampleCount: number;
        };
        EvaluationReportOverviewResponse: {
            recommendationAssessment: string;
            brandPerception: string;
            recommendationIndex: components["schemas"]["EvaluationRecommendationIndexResponse"];
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
            coverage: components["schemas"]["EvaluationCoverageResponse"];
        };
        EvaluationPlatformReportResponse: {
            platformKey: string;
            platformLabel: string;
            validSampleCount: number;
            totalSampleCount: number;
            validOpenSampleCount: number;
            mentionCount: number;
            mentionRate: number;
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
        };
        EvaluationEvidenceSummaryResponse: {
            sampleCount: number;
            platforms: string[];
        };
        EvaluationThemeResponse: {
            themeId: string;
            label: string;
            summary: string;
            evidence: components["schemas"]["EvaluationEvidenceSummaryResponse"];
        };
        EvaluationThemesResponse: {
            positive: components["schemas"]["EvaluationThemeResponse"][];
            negative: components["schemas"]["EvaluationThemeResponse"][];
        };
        EvaluationCompetitorResponse: {
            groupId: string;
            displayName: string;
            occurrenceCount: number;
            platforms: string[];
            typicalPosition: components["schemas"]["EvaluationTypicalPositionResponse"];
        };
        EvaluationDirectionResponse: {
            directionId: string;
            currentProblem: string;
            recommendedDirection: string;
            intendedImprovement: string;
            evidence: components["schemas"]["EvaluationEvidenceSummaryResponse"];
        };
        EvaluationReportDocumentResponse: {
            overview: components["schemas"]["EvaluationReportOverviewResponse"];
            platforms: components["schemas"]["EvaluationPlatformReportResponse"][];
            themes: components["schemas"]["EvaluationThemesResponse"];
            competitors: components["schemas"]["EvaluationCompetitorResponse"][];
            directions: components["schemas"]["EvaluationDirectionResponse"][];
            limitations: string[];
        };
        EvaluationHighlightRangeResponse: {
            start: number;
            end: number;
            exactText: string;
            /** @enum {string} */
            kind: "TARGET" | "POSITIVE" | "NEGATIVE" | "MIXED";
        };
        EvaluationReportSampleResponse: {
            id: string;
            platformKey: string;
            platformLabel: string;
            /** @enum {string} */
            availability: "INCLUDED" | "NOT_INCLUDED";
            mentioned: boolean | null;
            position: number | null;
            cardInterpretation: string | null;
            originalAnswer: string | null;
            highlightUnavailable: boolean;
            highlights: components["schemas"]["EvaluationHighlightRangeResponse"][];
        };
        EvaluationReportQuestionResponse: {
            id: string;
            /** @enum {string} */
            kind: "BRAND_DIRECTED" | "INDUSTRY_RECOMMENDATION" | "CHARACTERISTIC_ONE" | "CHARACTERISTIC_TWO";
            ordinal: number;
            content: string;
            samples: components["schemas"]["EvaluationReportSampleResponse"][];
        };
        EvaluationReportResponse: {
            id: string;
            runId: string;
            definitionId: string;
            brandId: string;
            brandSnapshot: components["schemas"]["EvaluationBrandSnapshotResponse"];
            brandInformationChanged: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            acceptedAt: string;
            document: components["schemas"]["EvaluationReportDocumentResponse"];
            questions: components["schemas"]["EvaluationReportQuestionResponse"][];
        };
        CurrentEvaluationReportResponse: {
            report: components["schemas"]["EvaluationReportResponse"] | null;
        };
        EvaluationReportSummaryResponse: {
            id: string;
            runId: string;
            brandId: string;
            brandName: string;
            brandInformationChanged: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            acceptedAt: string;
            recommendationIndex: number;
            mentionRate: number;
            validSampleCount: number;
            totalSampleCount: number;
        };
        EvaluationReportHistoryResponse: {
            items: components["schemas"]["EvaluationReportSummaryResponse"][];
            nextCursor: string | null;
        };
        MediaCatalogRevisionResponse: {
            revision: string;
        };
        MediaCategoryResponse: {
            /** @enum {string} */
            id: "CENTRAL_MEDIA" | "PORTAL_MEDIA" | "LOCAL_MEDIA" | "VERTICAL_MEDIA" | "CONTENT_PLATFORM" | "OVERSEAS_MEDIA";
            label: string;
        };
        MediaResourceExampleResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            /** @enum {string} */
            publicationMode: "FIRST_PUBLISH" | "REPOST";
        };
        MediaPlatformCustomerResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            description?: string | null;
            logoUrl?: string | null;
            /** @enum {string} */
            regionScope: "DOMESTIC" | "OVERSEAS";
            categories: ("CENTRAL_MEDIA" | "PORTAL_MEDIA" | "LOCAL_MEDIA" | "VERTICAL_MEDIA" | "CONTENT_PLATFORM" | "OVERSEAS_MEDIA")[];
            pointPrice: number;
            listingRevision: number;
            examples: components["schemas"]["MediaResourceExampleResponse"][];
        };
        MediaPlatformPageResponse: {
            items: components["schemas"]["MediaPlatformCustomerResponse"][];
            /** Format: uuid */
            nextCursor?: string | null;
        };
        MediaListingAdminResponse: {
            /** @enum {string} */
            status: "DRAFT" | "ON_SHELF" | "PAUSED" | "OFF_SHELF";
            pointPrice?: number | null;
            revision: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaPlatformAdminResponse: {
            /** Format: uuid */
            id: string;
            normalizedName: string;
            displayName: string;
            aliases: string[];
            description?: string | null;
            logoUrl?: string | null;
            /** @enum {string} */
            regionScope: "DOMESTIC" | "OVERSEAS";
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED";
            categories: ("CENTRAL_MEDIA" | "PORTAL_MEDIA" | "LOCAL_MEDIA" | "VERTICAL_MEDIA" | "CONTENT_PLATFORM" | "OVERSEAS_MEDIA")[];
            listing?: components["schemas"]["MediaListingAdminResponse"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaSupplySourceResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            contactName?: string | null;
            contactMethod?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            notes?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaResourceAdminResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            platformId: string;
            /** Format: uuid */
            supplySourceId: string;
            resourceName: string;
            accountIdentifier?: string | null;
            accountUrl?: string | null;
            /** @enum {string} */
            publicationMode: "FIRST_PUBLISH" | "REPOST";
            /** @enum {string} */
            status: "ACTIVE" | "PAUSED" | "ARCHIVED";
            /** @enum {string} */
            publicVisibility: "HIDDEN" | "FULL" | "MASKED";
            publicAlias?: string | null;
            /** @enum {string} */
            qualityTier: "HIGH" | "MEDIUM" | "LOW";
            procurementCostFen?: number | null;
            caseUrl?: string | null;
            publicationNotes?: string | null;
            source: components["schemas"]["MediaSupplySourceResponse"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaCatalogAuditResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actorAccountId: string;
            entityType: string;
            /** Format: uuid */
            entityId: string;
            action: string;
            reason: string;
            beforeState?: Record<string, never> | null;
            afterState?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        EvaluationReportNotificationTargetResponse: {
            /** @enum {string} */
            kind: "EVALUATION_REPORT";
            brandId: string;
            runId: string;
            reportId: string;
        };
        EvaluationRetryNotificationTargetResponse: {
            /** @enum {string} */
            kind: "EVALUATION_RETRY";
            brandId: string;
            runId: string;
        };
        NotificationResponse: {
            id: string;
            /** @enum {string} */
            kind: "EVALUATION_COMPLETED" | "EVALUATION_RETRY_REQUIRED";
            title: string;
            summary: string;
            target: components["schemas"]["EvaluationReportNotificationTargetResponse"] | components["schemas"]["EvaluationRetryNotificationTargetResponse"];
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            readAt: string | null;
        };
        NotificationListResponse: {
            items: components["schemas"]["NotificationResponse"][];
            unreadCount: number;
            nextCursor: string | null;
        };
        NotificationReadAllResponse: {
            unreadCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    FoundationController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationRecordResponse"];
                };
            };
        };
    };
    FoundationController_backlog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBacklogResponse"];
                };
            };
        };
    };
    FoundationController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationRecordResponse"];
                };
            };
        };
    };
    FoundationController_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IdentityController_requestChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestChallengeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
        };
    };
    IdentityController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteSessionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    IdentityController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    IdentityController_deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"][];
                };
            };
        };
    };
    BrandController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandMutationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    BrandController_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"] | null;
                };
            };
        };
    };
    BrandController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandMutationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    BrandController_selectCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandResponse"];
                };
            };
        };
    };
    BrandReferenceController_industries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryCatalogResponse"];
                };
            };
        };
    };
    BrandReferenceController_provinces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOptionListResponse"];
                };
            };
        };
    };
    BrandReferenceController_cities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityRegionOptionListResponse"];
                };
            };
        };
    };
    BrandReferenceController_terminals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalRegionOptionListResponse"];
                };
            };
        };
    };
    EvaluationController_currentReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentEvaluationReportResponse"];
                };
            };
        };
    };
    EvaluationController_reportHistory: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportHistoryResponse"];
                };
            };
        };
    };
    EvaluationController_reportDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: string;
                brandId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReportResponse"];
                };
            };
        };
    };
    EvaluationController_prepareDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDefinitionResponse"];
                };
            };
        };
    };
    EvaluationController_startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
        };
    };
    EvaluationController_retryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
        };
    };
    MediaCatalogController_revision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCatalogRevisionResponse"];
                };
            };
        };
    };
    MediaCatalogController_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCategoryResponse"][];
                };
            };
        };
    };
    MediaCatalogController_platforms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformPageResponse"];
                };
            };
        };
    };
    MediaCatalogController_platform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformCustomerResponse"];
                };
            };
        };
    };
    MediaAdminController_platforms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"][];
                };
            };
        };
    };
    MediaAdminController_createPlatform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_platform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_deletePlatform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaAdminController_updatePlatform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_listing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPlatformAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaSupplySourceResponse"][];
                };
            };
        };
    };
    MediaAdminController_createSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaSupplySourceResponse"];
                };
            };
        };
    };
    MediaAdminController_deleteSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaAdminController_updateSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaSupplySourceResponse"];
                };
            };
        };
    };
    MediaAdminController_resources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResourceAdminResponse"][];
                };
            };
        };
    };
    MediaAdminController_createResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResourceAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaAdminController_updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResourceAdminResponse"];
                };
            };
        };
    };
    MediaAdminController_audits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCatalogAuditResponse"][];
                };
            };
        };
    };
    NotificationController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
        };
    };
    NotificationController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationReadAllResponse"];
                };
            };
        };
    };
    NotificationController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
        };
    };
    NotificationController_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
